// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave.RouteTypeProvider")>]
[<assembly: AssemblyProductAttribute("Suave.RouteTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("A Type Provider helping to create strongly typed routes like WebApi format")>]
[<assembly: AssemblyVersionAttribute("0.0.4")>]
[<assembly: AssemblyFileVersionAttribute("0.0.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Suave.RouteTypeProvider"
    let [<Literal>] AssemblyProduct = "Suave.RouteTypeProvider"
    let [<Literal>] AssemblyDescription = "A Type Provider helping to create strongly typed routes like WebApi format"
    let [<Literal>] AssemblyVersion = "0.0.4"
    let [<Literal>] AssemblyFileVersion = "0.0.4"
